version: '3.1'
services:
version: '3.1'
services:

  addice:
    image: addiec
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 4200:4200
    volumes:
      - ./volumes/logs:/var/log/nginx
