FROM nginx:1.11.8

RUN apt-get update && \
	apt-get install -yqq python3 && \
	apt-get clean

ENV ENVIRONMENT local
ENV PUBLIC_URL https://localhost

ADD nginx/nginx.conf /etc/nginx/nginx.conf
ADD nginx/nginx.logging.conf /etc/nginx/nginx.logging.conf
ADD addiec /var/www/addiec
ADD init.py /var/www/addiec
ADD start.sh /var/www/addiec

CMD ["/var/www/addiec/start.sh"]